### ISSUE TITLE
[Main task] showing template2.0 with display factory

### ISSUE THREAD

**Issue by vadim9999** [LLazyEmail/markdown-to-email#1332]
Main task: https://github.com/LLazyEmail/markdown-to-email/issues/1336

the video in Asana

Package `atherdon-old-newsletter-js-outertemplate` - repository https://github.com/LLazyEmail/_trying-lit

- [x] https://github.com/LLazyEmail/markdown-to-email/issues/1334
- [x] #1344 
- [x] #1355
- [x] https://github.com/LLazyEmail/markdown-to-email/issues/1359

**Comment by atherdon** [comment]
Это прямо большой таск будет.

сразу могу предложить такие шаги:
- делать в feature/branch
- заменить функционал Literals на простые компоненты.(например взять и заменить парочку литералов как **strong** - которые очень легко будет дебажить)
- попробывать параллельно с методом fullTemplate расположить строку из displayMain и попробывать передать туда какие то данные.

задчи с литералами и с внешней частью темплейта можно даже делать параллельно, потому что они задействованы в разных частях проекта.

если сделаешь это as subtasks @vadim9999  - закину туда более детальное описание

**Comment by vadim9999** [comment]
@atherdon have we done migration to the template 2.0? can we close this task?

**Comment by atherdon** [comment]
I assume yes, closing it now
