### ISSUE TITLE
[Sub Task] updating "fullTemplate" logic

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/markdown-to-email#1344]
### параллельно с методом fullTemplate расположить строку из displayMain и попробывать передать туда какие то данные.

1. В index у нас вызывается метод `generateFullTemplate2` 

![image](https://user-images.githubusercontent.com/1469198/179708197-c11568e2-81ae-4d85-9d3c-e98aaf350894.png)

2. вот generateFullTemplate2

![image](https://user-images.githubusercontent.com/1469198/179712109-b12dba62-8616-48e5-8246-f3c4a432a42c.png)

3. Потом мы вызываем parse.

![image](https://user-images.githubusercontent.com/1469198/179708452-88075fc4-37ca-460b-9929-b58e9d674b9d.png)

4. configureReplacer 

...

В какой то момент мы вызываем fullTemplate.js который сделал Кольмиллер.
Этот темлейт мне ненравится и он не решает наших задач, так как должен.

![image](https://user-images.githubusercontent.com/1469198/179709487-c366deb6-e226-4386-9d5d-fd5e9dba970f.png)

### Задача

Нам нужно попробывать паралельно вытащить строку, сгенерированную с помощью строки `trying_lit/MainDisplay`.
![image](https://user-images.githubusercontent.com/1469198/179711527-ca9fb065-db8b-4201-bbec-e4eb0abf58e5.png)

Єта версия не является идеальной, потому что мы посути должны передавать контент и другие настройки извне. 
но при этом тесты в trying_lit показывают то что MainDisplay возвращает строку, которая похожа на результат работы `fullTemplate()` но при этом собирается из отдельных частей.

**Comment by atherdon** [comment]
сейчас в trying-lit

контент передается статический. мне он нужен был чтобы провалидировать работу.

![image](https://user-images.githubusercontent.com/1469198/180264523-d1f36cec-66c5-41f8-8152-02da6905296b.png)

есть 2 варианта решения нашей проблемы

1. вместо этой функции мы просто передаем строку `{content}` и наш реплейсер это должен хавать.

т.е. 

```
let addon1 = {
  footer: FooterHTMLString,

  logoTop: logoTopComponent(),
  logoBottom: logoBottomComponent(),
  content: "{content}",
  // content: '[[THIS IS PLACE FOR A CONTENT INSIDE]',
  previewText: previewTextComponent('[AMA PREVIEW TEXT]'),
};

```
сделает похожий темплейт как есть у нас сейчас.

2. вариант более сложный но правильный. нам нужно будет извне передать наш контент и собрать "display" у нас в генераторе. или например просто добавить функционала в trying_lit.
рано или поздно нам прийдется это сделать, чтобы извне пихать нужные нам переменные

**Comment by vadim9999** [comment]
@atherdon let`s do the second case

**Comment by vadim9999** [comment]
@atherdon in the result I have to create this object in generator and pass it in the printMain function?
![image](https://user-images.githubusercontent.com/35640573/180266569-6ab036c5-396b-45bb-b1a5-56c97fc866aa.png)
