### ISSUE TITLE
[Sub task] connect typography of nmtg (recipes template)

### ISSUE THREAD

**Issue by vadim9999** [LLazyEmail/markdown-to-email#1383]
Main task: #1340 
Repository: https://github.com/LLazyEmail/nomoretogo_email_template/tree/main/sub-modules/typography
The package to use `nmtg-template-mailerlite-typography`

**Comment by atherdon** [comment]
https://github.com/LLazyEmail/documentation/blob/main/docs/generator/test/improvements.md#task-14
