### ISSUE TITLE
tried to `yarn run dev:parseFull` and get an error

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/markdown-to-email#1453]
![image](https://user-images.githubusercontent.com/1469198/182575262-3bbf5d41-69e4-4e8e-95cf-60b4832392fb.png)

**Comment by atherdon** [comment]
same with `prod:parseFull`

**Comment by vadim9999** [comment]
ok, I will check it

**Comment by vadim9999** [comment]
found this bug, I will merge a fix in the PR with connecting typography

**Comment by vadim9999** [comment]
@atherdon fixed
