### ISSUE TITLE
paragrapf wrapper function 

### ISSUE THREAD

**Issue by Oleh8978** [LLazyEmail/markdown-to-email#268]
![image](https://user-images.githubusercontent.com/53382946/103446417-00f12900-4c88-11eb-842b-70e1082ce7e3.png)
line is undefined
![image](https://user-images.githubusercontent.com/53382946/103446421-1403f900-4c88-11eb-96cf-1939738c2e9b.png)

and reg expr 
![image](https://user-images.githubusercontent.com/53382946/103446431-3ac22f80-4c88-11eb-82f0-25eca30f37f5.png)

where I found it: 
![image](https://user-images.githubusercontent.com/53382946/103446450-7ceb7100-4c88-11eb-9ce2-9177da36eec8.png)
what we have we are calling parse wrapper here and we are not giving arguments as well line is undefined, what we have about paragraps it is \r\n(.+?)\r\n
and the screen shot from compiller 
as I understood it should take care about paragraps 
![image](https://user-images.githubusercontent.com/53382946/103446579-e28c2d00-4c89-11eb-98c1-5f7a3a08215a.png)

okay what we can do it is 
![image](https://user-images.githubusercontent.com/53382946/103446597-1bc49d00-4c8a-11eb-8538-86e6e08782b1.png)

just put enter to show it 
have questions and willing to fix it as well work on the issues 
I have idea how to fix everything here

**Comment by atherdon** [comment]
ok, now it's more clear for me.

first of all - it's related to full template generation.

second of all, we have a custom made tag, that related to the sponsorship block in our newsletters.

here is details: https://github.com/atherdon/markdown-to-email#sponsorship

here how it looks

![image](https://user-images.githubusercontent.com/1469198/103447179-5fbaa080-4c90-11eb-95ca-7b1efce34df2.png)


no, we cant separate it into few parts. it's a thing that contains 3 parts.


question 1: did you tried the convert the same template, but by using code from https://github.com/atherdon/markdown-to-email/tree/plain-working-version branch?
if it didn't work there as well - it means that it was broken for a long time.

my solution will be: let's simplify the logic of this method and fix it. as it's a very separate thing from the main content part - I don't worried about breaking everything else.


plus, I'm not sure that it should be related to paragraphs.
I mean, paragraphs, as default copy - should work after our changes.

and it this thing is an addon - let's make a separated function for it, and not call it a paragraph. Tell me if it's not clear and I will record a video for that 

cc @Oleh8978
