### ISSUE TITLE
next steps

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/markdown-to-email#320]
- finish separation into a few sub-modules

- react components tree generation from plain js

наверное нам нужно попробывать сделать\закончить отдельный метод, который позволит внутри текущего модуля генерировать DOM из react components. Основная идея простая - мне ненравится то что мы храним куски нашего email template в js файлах. это глупо. и в 2021 году есть гораздо более удобные и специфические задачи для этого. мы в ноябре начали подготовку к версии 2.0 генератора - которая темлейт будет хранить в react components и позволит нам играться
с другими вариантами layouts - при этом ничего не ломая. 

Чуть позже нам нужно будет перегнать весь процесс на react - если захотите, можете посмотреть код внутри [react ветки](https://github.com/atherdon/markdown-to-email/tree/react-components-stage-zero)

чтобы не начинать переходить на версию 2.0 генератора и проверить - можем ли мы сделать дерево из react тегов - я перенес их в отдельную папку, с похожей структурой.

модуль, в котором хранится старая версия react components находится тут.
https://github.com/atherdon/markdown-to-email/blob/master/package/generator-react-components/package.json
нам этой версии сейчас будет достаточно, чтобы понять что эта идея работает, и что можно легко заменить на react components

**Comment by atherdon** [comment]
cc @kolserdav это второй таск который можно тоже начать делать в этом проекте

**Comment by kolserdav** [comment]
>наверное нам нужно попробывать сделать\закончить отдельный метод, который позволит внутри текущего модуля генерировать DOM из react components. Основная идея простая - мне ненравится то что мы храним куски нашего email template в js файлах. это глупо. и в 2021 году есть гораздо более удобные и специфические задачи для этого. мы в ноябре начали подготовку к версии 2.0 генератора
>
Не совсем понимаю что и где и для чего нужно сделать

**Comment by atherdon** [comment]
поидее - когда у нас будут 3 под-модуля рабочих - мы красиво меняем
подмодуль layouts, в котором строки с plain HTML, на подмодуль react
components. и доделываем метод для `parse:react` - тогда генератор будет
собирать нам файл, в котором будут реакт компоненты внутри(а это будет
гораздо короче файл).

просто это переходный момент, поэтому он не очень понятный.

>
