### ISSUE TITLE
full-template report

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/markdown-to-email#355]
- [x] `[separator]` => `***`
- [ ] preview to check
- [ ] image should be resized or applied like 300x300 or something(https://github.com/atherdon/newsletters/pull/281#issuecomment-816833497)

**Comment by vadym9** [comment]
@atherdon what is the status of resizing images?

**Comment by vadim9999** [comment]
@atherdon what is the status of resizing images?

**Comment by vadim9999** [comment]
@atherdon I have just seen commit about new template in newsletters

**Comment by atherdon** [comment]
no status at this moment. i'm not sure if it's doable quickly here

**Comment by atherdon** [comment]
I think we'll wait for transition to react. and I hope there we'll be able to solve it

**Comment by vadim9999** [comment]
I think this task will take about 2-5 hours because we can't resize all images to 300x300px, it will lose quality

**Comment by atherdon** [comment]
for me resizing is low priority right now.
because I don't know what is the best way right now

**Comment by vadim9999** [comment]
bug wtih PREVIEW_TEXT is hard to replay or even impossible without sending envelop and checking it out, I have no access to send letters myself

**Comment by vadim9999** [comment]
Maybe you can do hard debug and fix it

**Comment by atherdon** [comment]
about Preview_text: i think we need to start with tests. can you do it and I'll fill a few examples there

**Comment by vadim9999** [comment]
Tests will not help us

**Comment by vadim9999** [comment]
we have it
![image](https://user-images.githubusercontent.com/35640573/114431243-f2d87000-9bc7-11eb-8300-87a6ce25c48a.png)

**Comment by atherdon** [comment]
ok, then give me some time and i'll add few more cases

**Comment by atherdon** [comment]
I see the problem. we didnt finish it

**Comment by atherdon** [comment]
@vadim9999 can you catch it from here?
link: https://github.com/atherdon/markdown-to-email/tree/main/src/tests/preview

**Comment by atherdon** [comment]
@vadim9999 tell me if you want to have a call

**Comment by vadim9999** [comment]
@atherdon yes we can have a quick 10 minutes call

**Comment by atherdon** [comment]
@vadim9999 was it completed? can we close this issue?

**Comment by vadim9999** [comment]
@atherdon I did do anything with this task

**Comment by atherdon** [comment]
not clear @vadim9999

**Comment by vadim9999** [comment]
I haven't done anything here

**Comment by atherdon** [comment]
got it

**Comment by atherdon** [comment]
not a problem at all

**Comment by vadim9999** [comment]
@atherdon did you broke generator for html?

**Comment by vadim9999** [comment]
[separator]

**Comment by vadim9999** [comment]
@atherdon created separator tag for MD to HTML and MD to React, added tests. 
Example of use:
```
text
[separator]
text
```

**Comment by atherdon** [comment]
wow wow wow - perfect!

>
