### ISSUE TITLE
simple tasks for main branch

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/markdown-to-email#403]
create 3 npm calls for generating full-template for 3 different cases(only plain version is necessary right now):
- full-template with advertising
- full template with advertising placeholders
- full-template without sponsors

https://github.com/atherdon/markdown-to-email/blob/main/package.json#L8

---

maybe we should do a custom markdown tag "[separator]" that will be replaced with `***`?
https://github.com/atherdon/markdown-to-email/issues/355

---

Can we add some warnings for preview text, for advertising blocks too?
https://github.com/atherdon/markdown-to-email/issues/355

---

can we clean up our constants package? https://github.com/atherdon/markdown-to-email/issues/356

---

switch from default RegExp that we have for links and create custom_link constant.

our goal will be to add URL param like `?ref=noonifications.tech` but let's use some working module, aka extension of `path` module.
because there can be tons of stupid issues that I want to skip

https://github.com/sindresorhus/query-string#stringifyobject-options

**Comment by coder-do** [comment]
> create 3 npm calls for generating full-template for 3 different cases(only plain version is necessary right now):

Этот момент не оч понятен

> maybe we should do a custom markdown tag "[separator]" that will be replaced with ***?

Это уже готово

> Can we add some warnings for preview text, for advertising blocks too?

Для previwText есть warning - когда парсим фулл контент в консоли выводится красным что previwText нету 

> can we clean up our constants package? #356

В этом не очень уверен

**Над последним пунктом Вадим работает как помню**

**Comment by atherdon** [comment]
< create 3 npm calls for generating full-template for 3 different cases(only plain version is necessary right now

сейчас у нас вызывается генератор с помощью одной команды.
и генерирует он темплейт только в том случае, когда есть вся информация сразу. - это первая команда.

но т.к. клиенты иногда тупят - мы генерируем темплейт, но не имеет в этот момент данных от спонсоров.
это будет вторая команда.

третья команда в package.json будет тоже генерировать темплейт, но в котором нету блоков от спонсора совсем. пример: https://www.noonifications.tech/w/FrS0z4j1mwy0iPFsU6N2Ig 
Сейчас, с помощью нашего генератора, такой layout не просто сделать. приходится потом руками удалять блоки

сс @coder-do
