### ISSUE TITLE
Fix generation from markdown to html (remaking function replaceMarkdown)

### ISSUE THREAD

**Issue by vadim9999** [LLazyEmail/markdown-to-email#908]
### How to reproduce
1. npm i
2. npm run parse

![image](https://user-images.githubusercontent.com/35640573/167688369-74ea162e-a97a-4293-aca3-5789513b08e8.png)

### Expected result 
Should be generation from markdown to html

This function should be remake. It should take only one argument.

https://github.com/LLazyEmail/markdown-to-email/blob/a5ca366a2ccdb759d8ffdff5ae8a357a6aaab60e/src/callbacks/replace-md.js#L41

This structure was before
```
this.replaceMDBinded(this._constants.REGEXP_STRONG, strong);
```
Should be working like this
```
this.replaceMDBinded("strong");
```

Maybe create a map that will look like:
```
const map = {
'strong': // other implementation
}
```

**Comment by atherdon** [comment]
marking as complete
