### ISSUE TITLE
Find solution for running checks on existing folder when running tests

### ISSUE THREAD

**Issue by vadim9999** [LLazyEmail/markdown-to-email#909]
At the moment in package.json scripts there are running checks on existing generated folders. After refactoring was removed file 
`checkFolders.js`. There was this two rows
 https://github.com/LLazyEmail/markdown-to-email/blob/a5ca366a2ccdb759d8ffdff5ae8a357a6aaab60e/src/parser.js#L22

![image](https://user-images.githubusercontent.com/35640573/167694521-4841e200-4539-43dd-b5ea-9dc9a0110e66.png)

Find solution for running two checks on folder existence (in future it can be more) while running tests and other running commands.
Maybe it can be created again file `checkFolders.js` but there will be problem with inconsistencies ES5 and ES6

**Comment by atherdon** [comment]
is this a method that you were looking for @vadim9999 

https://github.com/LLazyEmail/generator-module/blob/main/src/utils.js#L62

**Comment by atherdon** [comment]
release 1.7 had this file, if you want to bring it back

https://github.com/LLazyEmail/markdown-to-email/blob/1.7/checkFolders.js

**Comment by atherdon** [comment]
i think we "fixed" it. in our strange way
